#!/bin/bash
#To be able to run it easily from calvin-base dir
SECDHT_TESTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
pushd ~/.calvin/sec_dht_security_test/
rm -r runtimes test 
popd
python $SECDHT_TESTDIR/cert_script.py
py.test --twisted --runslow --runinteractive $SECDHT_TESTDIR/test_dht_server_nice2.py -s & 
py.test --twisted --runslow --runinteractive $SECDHT_TESTDIR/test_dht_server_nice.py -s &
py.test --twisted --runslow --runinteractive $SECDHT_TESTDIR/test_dht_server_nice3.py -s &
py.test --twisted --runslow --runinteractive $SECDHT_TESTDIR/test_dht_server_evil.py -s &

#py.test --twisted --runslow --runinteractive --loglevel DEBUG --logfile=/tmp/calvinlog_evil $SECDHT_TESTDIR/test_dht_server_evil.py
