#!/bin/bash
#To be able to run it easily from calvin-base dir
SECDHT_TESTDIR=~/Calvin/secure_dht2/calvin/runtime/south/plugins/storage/twistedimpl/securedht/tests
echo $SECDHT_TESTDIR
pushd ~/.calvin/sec_dht_security_test/
rm -r runtimes test
popd
python $SECDHT_TESTDIR/cert_script.py
py.test --twisted --runslow --runinteractive $SECDHT_TESTDIR/test_dht_server_nice.py
py.test --twisted --runslow --runinteractive $SECDHT_TESTDIR/test_dht_server_nice2.py
py.test --twisted --runslow --runinteractive $SECDHT_TESTDIR/test_dht_server_nice3.py
py.test --twisted --runslow --runinteractive $SECDHT_TESTDIR/test_dht_server_nice4.py

#py.test --twisted --runslow --runinteractive --loglevel DEBUG --logfile=/tmp/calvinlog_1 $SECDHT_TESTDIR/test_dht_server_nice.py -s &
#py.test --twisted --runslow --runinteractive --loglevel DEBUG --logfile=/tmp/calvinlog_2 $SECDHT_TESTDIR/test_dht_server_nice2.py -s &
#py.test --twisted --runslow --runinteractive --loglevel DEBUG --logfile=/tmp/calvinlog_3 $SECDHT_TESTDIR/test_dht_server_nice3.py -s &
#py.test --twisted --runslow --runinteractive --loglevel DEBUG --logfile=/tmp/calvinlog_4 $SECDHT_TESTDIR/test_dht_server_nice4.py -s &


