#!/bin/bash
pushd ~/.calvin/security/test/
rm -r private runtimes newcerts certs index* node* serial* evil* cacert.pem
popd
python ./cert_script.py
py.test --twisted --runslow --runinteractive test_dht_server_nice2.py -s & 
py.test --twisted --runslow --runinteractive test_dht_server_nice.py -s &
py.test --twisted --runslow --runinteractive test_dht_server_nice3.py -s &
py.test --twisted --runslow --runinteractive test_dht_server_evil.py -s &
