#!/bin/bash
WORKDIR=$PWD
cd ~/.calvin/security/test/
rm -r private runtimes newcerts certs index* node* serial* evil* cacert.pem
cd "$WORKDIR"
python ./cert_script.py
py.test --twisted --runslow --runinteractive tests/test_dht_server_nice2.py -s &
py.test --twisted --runslow --runinteractive tests/test_dht_server_nice.py -s &
py.test --twisted --runslow --runinteractive tests/test_dht_server_nice3.py -s &
